// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Zak Noble-Clarke
#version 450
layout(local_size_x = 1) in;
layout(set = 0, binding = 0) buffer Target { uint values[]; } target;
layout(set = 0, binding = 1) buffer Alias { uint values[]; } alias;
layout(set = 0, binding = 2) buffer Result { uint values[]; } result;
layout(push_constant) uniform Range { uint count; } range;
void main()
{
    target.values[range.count] = 0xdeadu;
    atomicAdd(target.values[range.count + 1u], 5u);
    result.values[0] = alias.values[0];
    result.values[1] = alias.values[1];
}
