// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Zak Noble-Clarke
#version 450
layout(local_size_x = 64) in;
layout(set = 0, binding = 0) buffer Source { uint values[]; } source;
layout(set = 0, binding = 1) buffer Destination { uint values[]; } destination;
layout(push_constant) uniform Range { uint count; } range;
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i < range.count)
        destination.values[i] = source.values[i];
}
